"""first migrate

Revision ID: 55adfbb8b134
Revises: 
Create Date: 2022-09-18 21:56:07.508143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55adfbb8b134'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=True),
    sa.Column('tipo', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ataque', sa.Integer(), nullable=True),
    sa.Column('defesa', sa.Integer(), nullable=True),
    sa.Column('velocidade', sa.Integer(), nullable=True),
    sa.Column('vida', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    op.drop_table('pokemon')
    op.drop_table('player')
    # ### end Alembic commands ###
